import { useCallback, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { ContentCopyRounded } from "@mui/icons-material";
import { Accordion, AccordionDetails, AccordionSummary, Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Container, Divider, Stack, TextField, ToggleButton, ToggleButtonGroup, Typography } from "@mui/material";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import api from "../api/axios";

export default function AssessmentReportPage() {
    const { assessmentId } = useParams(); const [data, setData] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
    const [query, setQuery] = useState(""); const [status, setStatus] = useState("all");
    const load = useCallback(async () => { setLoading(true); try { const response = await api.get(`/assessments/${assessmentId}`); setData(response.data); } catch { setError("This assessment or its reports could not be loaded."); } finally { setLoading(false); } }, [assessmentId]);
    useEffect(() => { load(); }, [load]);
    if (loading) return <Stack minHeight="60vh" alignItems="center" justifyContent="center"><CircularProgress /></Stack>;
    if (error || !data) return <Container sx={{ py: 5 }}><Alert severity="error">{error}</Alert></Container>;
    const { assessment, attempts } = data; const link = `${window.location.origin}/assessment/${assessment.shareToken}`;
    const visibleAttempts = attempts.filter((attempt) => (status === "all" || attempt.status === status) && `${attempt.candidateName} ${attempt.candidateEmail}`.toLowerCase().includes(query.trim().toLowerCase()));
    const toggleStatus = async () => { const status = assessment.status === "active" ? "closed" : "active"; await api.patch(`/assessments/${assessmentId}`, { status }); setData((current) => ({ ...current, assessment: { ...current.assessment, status } })); };
    const exportCsv = () => { const quote = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`; const rows = [["Candidate", "Email", "Status", "Overall score", "Round", "Question", "Answer", "Follow-up question", "Follow-up answer", "AI score", "AI feedback"]]; attempts.forEach((attempt) => attempt.rounds.forEach((round) => round.questions.forEach((question) => rows.push([attempt.candidateName, attempt.candidateEmail, attempt.status, attempt.overallScore ?? "", round.name, question.text, question.answer, question.followUpQuestion, question.followUpAnswer, question.score ?? "", question.feedbackComment])))); const blob = new Blob([rows.map((row) => row.map(quote).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${assessment.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-reports.csv`; anchor.click(); URL.revokeObjectURL(url); };
    return <Container maxWidth="lg" sx={{ py: { xs: 3, md: 6 } }}>
        <Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" gap={2}><Box><Stack direction="row" gap={1} alignItems="center"><Typography component="h1" variant="h3" fontWeight={850}>{assessment.title}</Typography><Chip label={assessment.status} color={assessment.status === "active" ? "success" : "default"} /></Stack><Typography color="text.secondary" mt={1}>{assessment.jobRole}{assessment.company ? ` · ${assessment.company}` : ""}</Typography></Box><Stack direction={{ xs: "column", sm: "row" }} gap={1} alignItems="center"><Button fullWidth startIcon={<ContentCopyRounded />} onClick={() => navigator.clipboard.writeText(link)}>Copy candidate link</Button><Button fullWidth disabled={!attempts.length} onClick={exportCsv}>Export CSV</Button><Button fullWidth variant="outlined" onClick={toggleStatus}>{assessment.status === "active" ? "Close assessment" : "Reopen assessment"}</Button></Stack></Stack>
        <Alert severity="warning" sx={{ my: 3 }}><strong>Human review required.</strong> Scores and feedback are AI-generated signals, not hiring decisions. Review the candidate’s evidence and apply a consistent rubric.</Alert>
        <Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" alignItems={{ xs: "stretch", md: "center" }} gap={2} mb={2}><Typography component="h2" variant="h5" fontWeight={800}>Candidate reports ({attempts.length})</Typography><Stack direction={{ xs: "column", sm: "row" }} gap={1}><TextField size="small" label="Search candidates" value={query} onChange={(event) => setQuery(event.target.value)} /><ToggleButtonGroup size="small" exclusive value={status} onChange={(_, value) => setStatus(value || "all")} aria-label="Filter candidate reports"><ToggleButton value="all">All</ToggleButton><ToggleButton value="started">In progress</ToggleButton><ToggleButton value="submitted">Submitted</ToggleButton></ToggleButtonGroup></Stack></Stack>
        {!attempts.length ? <Alert severity="info">No candidates have started yet.</Alert> : !visibleAttempts.length ? <Alert severity="info">No candidate reports match these filters.</Alert> : <Stack spacing={2}>{visibleAttempts.map((attempt) => <Card variant="outlined" key={attempt._id}><CardContent><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" gap={1}><Box><Typography component="h3" variant="h6" fontWeight={800}>{attempt.candidateName}</Typography><Typography variant="body2" color="text.secondary">{attempt.candidateEmail} · Started {new Date(attempt.startedAt).toLocaleString()}</Typography></Box><Stack direction="row" gap={1}><Chip label={attempt.status === "started" ? "In progress" : "Submitted"} color={attempt.status === "submitted" ? "success" : "warning"} />{attempt.status === "submitted" && <Chip label={`${attempt.overallScore ?? 0}/10 AI score`} color="primary" />}</Stack></Stack>
            <Divider sx={{ my: 2 }} />{attempt.rounds.map((round) => <Accordion disableGutters key={round._id}><AccordionSummary expandIcon={<ExpandMoreIcon />}><Stack direction="row" justifyContent="space-between" width="100%" pr={1}><Typography fontWeight={750}>{round.name}</Typography>{attempt.status === "submitted" && <Typography color="text.secondary">{round.score ?? 0}/10</Typography>}</Stack></AccordionSummary><AccordionDetails><Stack spacing={3}>{round.questions.map((question, index) => <Box key={question._id}><Typography fontWeight={750}>{index + 1}. {question.text}</Typography><Typography sx={{ whiteSpace: "pre-wrap", mt: 1 }}>{question.answer || "Not answered"}</Typography>{question.followUpQuestion && <Box sx={{ mt: 2, pl: 2, borderLeft: "3px solid", borderColor: "primary.light" }}><Typography fontWeight={700}>AI follow-up: {question.followUpQuestion}</Typography><Typography sx={{ whiteSpace: "pre-wrap", mt: .5 }}>{question.followUpAnswer || "Not answered"}</Typography></Box>}{attempt.status === "submitted" && <Alert severity="info" sx={{ mt: 2 }}><Typography fontWeight={700}>AI assessment · {question.score ?? 0}/10</Typography><Typography variant="caption" color="text.secondary">Indicative rubric: correctness, clarity, and depth.</Typography><Typography mt={.5}>{question.feedbackComment}</Typography>{question.suggestions?.length > 0 && <Box component="ul" sx={{ mb: 0 }}>{question.suggestions.map((suggestion) => <li key={suggestion}>{suggestion}</li>)}</Box>}</Alert>}</Box>)}</Stack></AccordionDetails></Accordion>)}</CardContent></Card>)}</Stack>}
    </Container>;
}
