import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Container, LinearProgress, Paper, Stack, Typography } from "@mui/material";
import api from "../api/axios";

export default function AssessmentPreviewPage() {
    const { assessmentId } = useParams(); const navigate = useNavigate();
    const [assessment, setAssessment] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
    const [roundIndex, setRoundIndex] = useState(0); const [questionIndex, setQuestionIndex] = useState(0);
    useEffect(() => { api.get(`/assessments/${assessmentId}/preview`).then(({ data }) => setAssessment(data)).catch(() => setError("Preview could not be loaded.")).finally(() => setLoading(false)); }, [assessmentId]);
    if (loading) return <Stack minHeight="60vh" alignItems="center" justifyContent="center"><CircularProgress /></Stack>;
    if (!assessment) return <Container maxWidth="sm" sx={{ py: 6 }}><Alert severity="error">{error}</Alert></Container>;
    const round = assessment.rounds[roundIndex]; const question = round.questions[questionIndex]; const total = assessment.rounds.reduce((sum, item) => sum + item.questions.length, 0); const position = assessment.rounds.slice(0, roundIndex).reduce((sum, item) => sum + item.questions.length, 0) + questionIndex + 1;
    const next = () => { if (questionIndex + 1 < round.questions.length) setQuestionIndex(questionIndex + 1); else if (roundIndex + 1 < assessment.rounds.length) { setRoundIndex(roundIndex + 1); setQuestionIndex(0); } };
    const previous = () => { if (questionIndex > 0) setQuestionIndex(questionIndex - 1); else if (roundIndex > 0) { const previousRound = roundIndex - 1; setRoundIndex(previousRound); setQuestionIndex(assessment.rounds[previousRound].questions.length - 1); } };
    return <Container maxWidth="lg" sx={{ py: { xs: 3, md: 5 } }}><Alert severity="info" sx={{ mb: 3 }} action={<Button color="inherit" onClick={() => navigate(`/assessments/${assessmentId}`)}>Exit preview</Button>}><strong>Recruiter preview.</strong> Nothing entered here is saved, scored, or counted as a candidate attempt.</Alert><Typography variant="overline" color="primary" fontWeight={800}>{assessment.company || "Candidate assessment"}</Typography><Typography component="h1" variant="h3" fontWeight={850}>{assessment.title}</Typography><Typography color="text.secondary" mt={1}>{assessment.jobRole} · {total} {total === 1 ? "question" : "questions"} · about {assessment.durationMinutes || 30} minutes</Typography>{assessment.candidateInstructions && <Alert severity="info" sx={{ mt: 3 }}>{assessment.candidateInstructions}</Alert>}<Paper variant="outlined" sx={{ p: { xs: 2, md: 4 }, mt: 3 }}><Typography component="h2" variant="h5" fontWeight={800}>Before you begin</Typography><Typography color="text.secondary" mt={1}>Candidates see identity, consent, integrity, camera, and support information here before starting.</Typography><Stack direction="row" gap={1} flexWrap="wrap" mt={2}><Chip label={assessment.inviteOnly ? "Invitation only" : "Anyone with link"} /><Chip label={assessment.followUpsEnabled ? "AI follow-ups enabled" : "No AI follow-ups"} />{assessment.integrity?.enabled && <Chip color="warning" label="Integrity consent required" />}{assessment.integrity?.requireCamera && <Chip color="warning" label="Camera required" />}{assessment.integrity?.requireFullscreen && <Chip color="warning" label="Fullscreen requested" />}</Stack></Paper><Stack direction="row" justifyContent="space-between" mt={4} mb={1}><Typography fontWeight={750}>Candidate progress</Typography><Typography>{position} of {total}</Typography></Stack><LinearProgress variant="determinate" value={total ? position / total * 100 : 0} sx={{ mb: 3, height: 8, borderRadius: 4 }} /><Card variant="outlined"><CardContent sx={{ p: { xs: 2, md: 3 } }}><Typography variant="overline" color="primary" fontWeight={800}>{round.name} · Question {questionIndex + 1} of {round.questions.length}</Typography><Typography component="h2" variant="h5" fontWeight={800}>{question.text}</Typography><Box sx={{ minHeight: 160, mt: 3, p: 2, border: "1px solid", borderColor: "divider", borderRadius: 2, color: "text.secondary" }}>{round.deliveryMode === "online-assessment" ? "Candidate code or written answer field" : round.deliveryMode === "system-design" ? "Interactive Excalidraw architecture canvas with written and voice explanation" : "Candidate answer field with voice input"}</Box><Stack direction="row" justifyContent="space-between" mt={2}><Button disabled={position === 1} onClick={previous}>Previous</Button><Button variant="contained" disabled={position === total} onClick={next}>Next question</Button></Stack></CardContent></Card></Container>;
}
