import { useCallback, useEffect, useState } from "react";
import { Link as RouterLink, useSearchParams } from "react-router-dom";
import { AddRounded, ArrowDownwardRounded, ArrowUpwardRounded, AutoAwesomeRounded, ContentCopyRounded, DeleteOutlineRounded } from "@mui/icons-material";
import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, CircularProgress, Collapse, Container, Divider, FormControlLabel, IconButton, Pagination, Paper, Stack, TextField, Tooltip, Typography } from "@mui/material";
import api from "../api/axios";

const emptyRound = () => ({ name: "Technical", description: "Role-specific knowledge and practical judgment", questionCount: 3, aiPrompt: "", questions: [] });
const initialForm = { title: "", company: "", jobRole: "", jobDescription: "", candidateInstructions: "", contactEmail: "", durationMinutes: 30, expiresAt: "", followUpsEnabled: true, rounds: [emptyRound()] };
const countRequestedInPrompt = (prompt) => { const match = prompt.match(/\b(?:generate|create|make)?\s*(10|[1-9])\s+questions?\b/i); return match ? Number(match[1]) : null; };

export default function AssessmentsPage() {
    const [searchParams, setSearchParams] = useSearchParams();
    const [items, setItems] = useState([]); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1);
    const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
    const [form, setForm] = useState(initialForm);
    const [generatingRound, setGeneratingRound] = useState(null); const [improvingQuestion, setImprovingQuestion] = useState("");
    const [showCreate, setShowCreate] = useState(searchParams.get("create") === "1");
    const load = useCallback(async () => { setLoading(true); setError(""); try { const { data } = await api.get("/assessments", { params: { page, limit: 8 } }); setItems(data.items || []); setTotalPages(data.totalPages || 1); } catch { setError("We couldn’t load your assessments."); } finally { setLoading(false); } }, [page]);
    useEffect(() => { load(); }, [load]);
    const setField = (key, value) => setForm((current) => ({ ...current, [key]: value }));
    const updateRound = (index, key, value) => setForm((current) => ({ ...current, rounds: current.rounds.map((round, position) => position === index ? { ...round, [key]: value } : round) }));
    const updateQuestion = (roundIndex, questionIndex, text) => setForm((current) => ({ ...current, rounds: current.rounds.map((round, position) => position === roundIndex ? { ...round, questions: round.questions.map((question, qPosition) => qPosition === questionIndex ? { ...question, text } : question) } : round) }));
    const addQuestion = (roundIndex) => setForm((current) => ({ ...current, rounds: current.rounds.map((round, position) => position === roundIndex ? { ...round, questions: [...round.questions, { text: "" }] } : round) }));
    const removeQuestion = (roundIndex, questionIndex) => setForm((current) => ({ ...current, rounds: current.rounds.map((round, position) => position === roundIndex ? { ...round, questions: round.questions.filter((_, qPosition) => qPosition !== questionIndex) } : round) }));
    const moveQuestion = (roundIndex, questionIndex, direction) => setForm((current) => ({ ...current, rounds: current.rounds.map((round, position) => { if (position !== roundIndex) return round; const questions = [...round.questions]; const target = questionIndex + direction; if (target < 0 || target >= questions.length) return round; [questions[questionIndex], questions[target]] = [questions[target], questions[questionIndex]]; return { ...round, questions }; }) }));
    const generateQuestions = async (roundIndex) => { const round = form.rounds[roundIndex]; if (!round.aiPrompt.trim()) { setError("Describe the topics, difficulty, or question style you want AI to generate."); return; } setGeneratingRound(roundIndex); setError(""); try { const requestedCount = countRequestedInPrompt(round.aiPrompt); const targetCount = requestedCount || Number(round.questionCount); const existing = round.questions.filter((question) => question.text.trim()); const remaining = Math.max(targetCount - existing.length, 1); const { data } = await api.post("/assessments/questions/generate", { company: form.company, jobRole: form.jobRole, jobDescription: form.jobDescription, roundName: round.name, roundDescription: round.description, prompt: round.aiPrompt, count: remaining, existingQuestions: existing.map((question) => question.text) }); setForm((current) => ({ ...current, rounds: current.rounds.map((item, position) => position === roundIndex ? { ...item, questionCount: targetCount, questions: [...existing, ...(data.questions || [])].slice(0, 10) } : item) })); } catch (err) { setError(err?.response?.data?.message || "AI couldn’t generate questions right now. You can add them manually."); } finally { setGeneratingRound(null); } };
    const improveQuestion = async (roundIndex, questionIndex) => { const question = form.rounds[roundIndex].questions[questionIndex]; if (!question.text.trim()) return; const key = `${roundIndex}-${questionIndex}`; setImprovingQuestion(key); setError(""); try { const { data } = await api.post("/assessments/questions/improve", { question: question.text, jobRole: form.jobRole, jobDescription: form.jobDescription, roundName: form.rounds[roundIndex].name }); updateQuestion(roundIndex, questionIndex, data.text); } catch (err) { setError(err?.response?.data?.message || "AI couldn’t improve this question right now."); } finally { setImprovingQuestion(""); } };
    const copyLink = async (token) => { await navigator.clipboard.writeText(`${window.location.origin}/assessment/${token}`); setSuccess("Candidate link copied."); };
    const create = async (event) => { event.preventDefault(); const rounds = form.rounds.map((round) => ({ ...round, questions: round.questions.map((question) => ({ text: question.text.trim() })).filter((question) => question.text), questionCount: round.questions.filter((question) => question.text.trim()).length })); if (rounds.some((round) => !round.questionCount)) { setError("Add or generate at least one question in every round before publishing."); return; } setSaving(true); setError(""); setSuccess(""); try { await api.post("/assessments", { ...form, expiresAt: form.expiresAt || undefined, rounds }); setForm(initialForm); setSuccess("Assessment created. Share its private link with candidates."); setShowCreate(false); setSearchParams({}); setPage(1); await load(); } catch (err) { setError(err?.response?.data?.message || "The assessment couldn’t be created. Check the details and try again."); } finally { setSaving(false); } };
    return <Container maxWidth="lg" sx={{ py: { xs: 3, md: 6 } }}>
        <Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" alignItems={{ xs: "stretch", sm: "flex-start" }} gap={2} mb={3}><Box><Typography component="h1" variant="h3" sx={{ fontSize: { xs: "2.45rem", sm: "3rem" } }} fontWeight={850}>Candidate assessments</Typography>
        <Typography color="text.secondary" sx={{ mt: 1 }}>Share consistent interviews and review private candidate reports.</Typography></Box><Button variant="contained" startIcon={<AddRounded />} onClick={() => { const next = !showCreate; setShowCreate(next); setSearchParams(next ? { create: "1" } : {}); }}>{showCreate ? "Cancel" : "Create assessment"}</Button></Stack>
        {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{success && <Alert severity="success" sx={{ mb: 2 }} onClose={() => setSuccess("")}>{success}</Alert>}
        <Typography component="h2" variant="h5" fontWeight={800} mb={2}>Your assessments</Typography>
        {loading ? <Stack alignItems="center" py={4}><CircularProgress /></Stack> : items.length === 0 ? <Alert severity="info" sx={{ mb: 3 }} action={!showCreate ? <Button color="inherit" onClick={() => setShowCreate(true)}>Create one</Button> : null}>No assessments yet.</Alert> : <Stack spacing={2} mb={4}>{items.map((item) => <Card variant="outlined" key={item._id}><CardContent><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" gap={2}><Box><Stack direction="row" gap={1} alignItems="center" flexWrap="wrap"><Typography component="h3" variant="h6" fontWeight={800}>{item.title}</Typography><Chip size="small" label={item.status} color={item.status === "active" ? "success" : "default"} /></Stack><Typography color="text.secondary">{item.jobRole}{item.company ? ` · ${item.company}` : ""}</Typography><Typography variant="body2" mt={1}>{item.submittedCount || 0} submitted · {item.attemptCount || 0} started</Typography></Box><Stack direction="row" alignItems="center"><Tooltip title="Copy candidate link"><IconButton onClick={() => copyLink(item.shareToken)}><ContentCopyRounded /></IconButton></Tooltip><Button component={RouterLink} to={`/assessments/${item._id}`} variant="outlined">View reports</Button></Stack></Stack></CardContent></Card>)}</Stack>}
        {totalPages > 1 && <Stack alignItems="center" sx={{ mb: 4 }}><Pagination page={page} count={totalPages} onChange={(_, value) => setPage(value)} /></Stack>}
        <Collapse in={showCreate} unmountOnExit>
        <Paper component="form" onSubmit={create} variant="outlined" sx={{ p: { xs: 2, md: 3 }, mb: 4 }}>
            <Typography component="h2" variant="h5" fontWeight={800}>Create assessment</Typography>
            <Stack spacing={2} sx={{ mt: 2 }}>
                <Stack direction={{ xs: "column", md: "row" }} spacing={2}><TextField required fullWidth label="Assessment title" value={form.title} onChange={(e) => setField("title", e.target.value)} /><TextField fullWidth label="Company (optional)" value={form.company} onChange={(e) => setField("company", e.target.value)} /><TextField required fullWidth label="Job role" value={form.jobRole} onChange={(e) => setField("jobRole", e.target.value)} /></Stack>
                <TextField required multiline minRows={4} label="Job description and success criteria" helperText="Include responsibilities, seniority, must-have skills, and what strong performance looks like. These details shape every generated question." value={form.jobDescription} onChange={(e) => setField("jobDescription", e.target.value)} inputProps={{ minLength: 20 }} />
                <TextField multiline minRows={2} label="Candidate instructions (optional)" value={form.candidateInstructions} onChange={(e) => setField("candidateInstructions", e.target.value)} />
                <Stack direction={{ xs: "column", md: "row" }} spacing={2}><TextField fullWidth type="email" label="Candidate support email (optional)" helperText="Shown to candidates if they need help." value={form.contactEmail} onChange={(e) => setField("contactEmail", e.target.value)} /><TextField fullWidth type="number" label="Estimated duration (minutes)" value={form.durationMinutes} onChange={(e) => setField("durationMinutes", e.target.value)} inputProps={{ min: 5, max: 240 }} /><TextField fullWidth label="Submission deadline (optional)" type="datetime-local" value={form.expiresAt} onChange={(e) => setField("expiresAt", e.target.value)} InputLabelProps={{ shrink: true }} /></Stack>
                <Divider /><Box><Typography component="h3" variant="h6" fontWeight={750}>Build the questions</Typography><Typography variant="body2" color="text.secondary">Add your own questions, ask AI to draft the rest, then edit and reorder everything before publishing.</Typography></Box>
                {form.rounds.map((round, index) => <Card variant="outlined" key={index}><CardContent><Stack spacing={2}><Stack direction={{ xs: "column", md: "row" }} spacing={2} alignItems="center"><TextField required fullWidth label="Round name" value={round.name} onChange={(e) => updateRound(index, "name", e.target.value)} /><TextField fullWidth label="What this round evaluates" value={round.description} onChange={(e) => updateRound(index, "description", e.target.value)} /><TextField required label="Target questions" type="number" value={round.questionCount} onChange={(e) => updateRound(index, "questionCount", e.target.value)} inputProps={{ min: 1, max: 10 }} sx={{ width: { xs: "100%", md: 170 } }} />{form.rounds.length > 1 && <Tooltip title="Remove round"><IconButton aria-label={`Remove ${round.name} round`} onClick={() => setField("rounds", form.rounds.filter((_, position) => position !== index))}><DeleteOutlineRounded /></IconButton></Tooltip>}</Stack>
                    <Stack direction={{ xs: "column", md: "row" }} spacing={1} alignItems="flex-start"><TextField fullWidth multiline minRows={2} label="Tell AI what to generate" placeholder="Generate 10 scenario-based questions from React performance, accessibility, and testing; senior difficulty." helperText="Mention topics, difficulty, format, or situations to cover. AI adds questions up to the target count." value={round.aiPrompt} onChange={(e) => updateRound(index, "aiPrompt", e.target.value)} /><Button variant="outlined" startIcon={generatingRound === index ? <CircularProgress size={18} /> : <AutoAwesomeRounded />} disabled={generatingRound !== null || !form.jobRole || form.jobDescription.length < 20} onClick={() => generateQuestions(index)} sx={{ minWidth: 190, mt: { md: 1 } }}>{generatingRound === index ? "Generating…" : "Generate with AI"}</Button></Stack>
                    <Stack spacing={1}>{round.questions.map((question, questionIndex) => <Stack key={questionIndex} direction="row" spacing={1} alignItems="flex-start"><TextField required fullWidth multiline label={`Question ${questionIndex + 1}`} value={question.text} onChange={(e) => updateQuestion(index, questionIndex, e.target.value)} inputProps={{ maxLength: 1000 }} /><Stack direction="row"><Tooltip title="Improve with AI"><span><IconButton aria-label={`Improve question ${questionIndex + 1} with AI`} disabled={!question.text.trim() || Boolean(improvingQuestion)} onClick={() => improveQuestion(index, questionIndex)}>{improvingQuestion === `${index}-${questionIndex}` ? <CircularProgress size={20} /> : <AutoAwesomeRounded />}</IconButton></span></Tooltip><Tooltip title="Move up"><span><IconButton aria-label={`Move question ${questionIndex + 1} up`} disabled={questionIndex === 0} onClick={() => moveQuestion(index, questionIndex, -1)}><ArrowUpwardRounded /></IconButton></span></Tooltip><Tooltip title="Move down"><span><IconButton aria-label={`Move question ${questionIndex + 1} down`} disabled={questionIndex === round.questions.length - 1} onClick={() => moveQuestion(index, questionIndex, 1)}><ArrowDownwardRounded /></IconButton></span></Tooltip><Tooltip title="Delete question"><IconButton aria-label={`Delete question ${questionIndex + 1}`} onClick={() => removeQuestion(index, questionIndex)}><DeleteOutlineRounded /></IconButton></Tooltip></Stack></Stack>)}</Stack>
                    <Stack direction="row" justifyContent="space-between" alignItems="center"><Button startIcon={<AddRounded />} disabled={round.questions.length >= 10} onClick={() => addQuestion(index)}>Add manual question</Button><Typography variant="caption" color={round.questions.length > Number(round.questionCount) ? "warning.main" : "text.secondary"}>{round.questions.length}/{round.questionCount} target questions</Typography></Stack>
                </Stack></CardContent></Card>)}
                <Box><Button startIcon={<AddRounded />} disabled={form.rounds.length >= 5} onClick={() => setField("rounds", [...form.rounds, emptyRound()])}>Add round</Button></Box>
                <FormControlLabel control={<Checkbox checked={form.followUpsEnabled} onChange={(e) => setField("followUpsEnabled", e.target.checked)} />} label="Let AI ask one contextual follow-up after each answer" />
                <Box><Button type="submit" variant="contained" disabled={saving}>{saving ? <CircularProgress size={22} color="inherit" /> : "Create and publish assessment"}</Button></Box>
            </Stack>
        </Paper></Collapse>
    </Container>;
}
