import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link as RouterLink, useParams } from "react-router-dom";
import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, CircularProgress, Container, FormControlLabel, LinearProgress, Link, Paper, Stack, TextField, Typography } from "@mui/material";
import api from "../api/axios";
import CodeEditorField from "../components/CodeEditorField";
import VoiceControls from "../components/VoiceControls";
import { useVoiceInput } from "../hooks/useVoiceInput";
import WebcamPreview from "../components/WebcamPreview";

export default function CandidateAssessmentPage() {
    const { shareToken } = useParams(); const storageKey = `assessment-attempt:${shareToken}`;
    const [assessment, setAssessment] = useState(null); const [attempt, setAttempt] = useState(null); const [attemptToken, setAttemptToken] = useState("");
    const [identity, setIdentity] = useState({ name: "", email: "" }); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [submitted, setSubmitted] = useState(false);
    const [consent, setConsent] = useState(false); const [integrityConsent, setIntegrityConsent] = useState(false); const [cameraReady, setCameraReady] = useState(false); const [dirty, setDirty] = useState({});
    const [activeRoundIndex, setActiveRoundIndex] = useState(0); const [activeQuestionIndex, setActiveQuestionIndex] = useState(0); const [codingEnabled, setCodingEnabled] = useState(false); const [spokenNotes, setSpokenNotes] = useState({}); const [focusedField, setFocusedField] = useState("answer");
    const autoStartedTargetsRef = useRef(new Set()); const focusedVoiceTargetRef = useRef("");
    const onTranscript = useCallback((target, text) => {
        if (window.speechSynthesis?.speaking) return;
        target = focusedVoiceTargetRef.current || target;
        const [prefix, roundValue, questionValue, field = "answer"] = String(target).split(":");
        if (prefix !== "candidate") return;
        const roundIndex = Number(roundValue); const questionIndex = Number(questionValue);
        const baseTarget = `candidate:${roundIndex}:${questionIndex}`;
        if (field === "spoken") { setSpokenNotes((current) => ({ ...current, [baseTarget]: `${current[baseTarget] || ""}${current[baseTarget] ? " " : ""}${text}` })); setDirty((current) => ({ ...current, [`${roundIndex}:${questionIndex}:answer`]: true })); return; }
        setDirty((current) => ({ ...current, [`${roundIndex}:${questionIndex}:${field === "followup" ? "followup" : "answer"}`]: true }));
        setAttempt((current) => current ? ({ ...current, rounds: current.rounds.map((round, ri) => ri === roundIndex ? { ...round, questions: round.questions.map((question, qi) => { if (qi !== questionIndex) return question; const key = field === "followup" ? "followUpAnswer" : "answer"; return { ...question, [key]: `${question[key] || ""}${question[key] ? " " : ""}${text}` }; }) } : round) }) : current);
    }, []);
    const candidateToolHeaders = useMemo(() => attemptToken ? { "X-Attempt-Token": attemptToken } : {}, [attemptToken]);
    const candidateToolBase = attempt ? `/assessments/public/${shareToken}/attempts/${attempt._id}` : "";
    const { listening, listeningTarget, interimText, micLevel, micPermission, inputDevices, selectedDeviceId, setSelectedDeviceId, supportsSTT, supportsTTS, startListening, stopListening, retargetListening, speakNow } = useVoiceInput({ onTranscript, transcribeEndpoint: candidateToolBase ? `${candidateToolBase}/transcribe` : "/stt/transcribe", transcribeHeaders: candidateToolHeaders, enableServerTranscription: assessment?.capabilities?.transcription !== false, skipAuthRedirect: true });
    useEffect(() => { (async () => { try { const invite = new URLSearchParams(window.location.search).get("invite"); const { data } = await api.get(`/assessments/public/${shareToken}`, { params: invite ? { invite } : undefined }); setAssessment(data); const saved = JSON.parse(localStorage.getItem(storageKey) || "null"); if (saved?.attempt && saved?.attemptToken) { setAttempt(saved.attempt); setAttemptToken(saved.attemptToken); } } catch { setError("This assessment link is invalid, closed, or expired."); } finally { setLoading(false); } })(); }, [shareToken, storageKey]);
    const persist = (nextAttempt, token = attemptToken) => { setAttempt(nextAttempt); localStorage.setItem(storageKey, JSON.stringify({ attempt: nextAttempt, attemptToken: token, savedAt: new Date().toISOString() })); };
    useEffect(() => { if (attempt && attemptToken) localStorage.setItem(storageKey, JSON.stringify({ attempt, attemptToken, savedAt: new Date().toISOString() })); }, [attempt, attemptToken, storageKey]);
    const start = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { const { data } = await api.post(`/assessments/public/${shareToken}/start`, { ...identity, integrityConsent }, { skipAuthRedirect: true }); setAttemptToken(data.attemptToken); persist(data.attempt, data.attemptToken); if (assessment.integrity?.requireFullscreen) document.documentElement.requestFullscreen?.().catch(() => {}); } catch (err) { setError(err?.response?.data?.message || "We couldn’t start your assessment."); } finally { setBusy(false); } };
    const checkCamera = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ video: true }); stream.getTracks().forEach((track) => track.stop()); setCameraReady(true); setError(""); } catch { setCameraReady(false); setError("Camera access is required for this assessment. Allow camera permission and try again."); } };
    useEffect(() => { if (!attempt || !attemptToken || !assessment?.integrity?.enabled) return undefined; const record = (type, metadata = {}) => api.post(`/assessments/public/${shareToken}/attempts/${attempt._id}/integrity-events`, { type, metadata }, { headers: { "X-Attempt-Token": attemptToken }, skipAuthRedirect: true }).catch(() => {}); const visibility = () => { if (document.hidden && assessment.integrity.trackFocus) record("tab_hidden"); }; const blur = () => assessment.integrity.trackFocus && record("window_blur"); const fullscreen = () => assessment.integrity.requireFullscreen && !document.fullscreenElement && record("fullscreen_exit"); const copy = () => assessment.integrity.trackClipboard && record("copy"); const paste = () => assessment.integrity.trackClipboard && record("paste"); const offline = () => record("offline"); const online = () => record("online"); document.addEventListener("visibilitychange", visibility); document.addEventListener("fullscreenchange", fullscreen); document.addEventListener("copy", copy); document.addEventListener("paste", paste); window.addEventListener("blur", blur); window.addEventListener("offline", offline); window.addEventListener("online", online); return () => { document.removeEventListener("visibilitychange", visibility); document.removeEventListener("fullscreenchange", fullscreen); document.removeEventListener("copy", copy); document.removeEventListener("paste", paste); window.removeEventListener("blur", blur); window.removeEventListener("offline", offline); window.removeEventListener("online", online); }; }, [assessment?.integrity, attempt, attemptToken, shareToken]);
    useEffect(() => { const warn = (event) => { if (!Object.keys(dirty).length) return; event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
    const answerKey = (roundIndex, questionIndex, followUp = false) => `${roundIndex}:${questionIndex}:${followUp ? "followup" : "answer"}`;
    const updateLocal = (roundIndex, questionIndex, key, value) => { setDirty((current) => ({ ...current, [answerKey(roundIndex, questionIndex, key === "followUpAnswer")]: true })); setAttempt((current) => ({ ...current, rounds: current.rounds.map((round, ri) => ri === roundIndex ? { ...round, questions: round.questions.map((question, qi) => qi === questionIndex ? { ...question, [key]: value } : question) } : round) })); };
    const saveAnswer = async (roundIndex, questionIndex, followUp = false, spokenExplanation) => { const question = attempt.rounds[roundIndex].questions[questionIndex]; const value = followUp ? question.followUpAnswer : question.answer; if (!value?.trim()) { setError("Write an answer before saving."); return false; } setBusy(true); setError(""); try { const body = followUp ? { roundIndex, questionIndex, followUpAnswer: value } : { roundIndex, questionIndex, answer: value, spokenExplanation: spokenExplanation || "" }; const { data } = await api.put(`/assessments/public/${shareToken}/attempts/${attempt._id}/answer`, body, { headers: { "X-Attempt-Token": attemptToken }, skipAuthRedirect: true }); persist(data.attempt); const key = answerKey(roundIndex, questionIndex, followUp); setDirty((current) => { const next = { ...current }; delete next[key]; return next; }); return true; } catch (err) { setError(err?.response?.data?.message || "Your answer could not be saved."); return false; } finally { setBusy(false); } };
    const questions = useMemo(() => attempt?.rounds?.flatMap((round) => round.questions) || [], [attempt]); const completed = questions.filter((question) => question.answer && (!question.followUpQuestion || question.followUpAnswer)).length;
    const activeRound = attempt?.rounds?.[activeRoundIndex]; const activeQuestion = activeRound?.questions?.[activeQuestionIndex]; const answerTarget = `candidate:${activeRoundIndex}:${activeQuestionIndex}`; const voiceTarget = `${answerTarget}:${focusedField}`;
    useEffect(() => { focusedVoiceTargetRef.current = voiceTarget; if (listening) autoStartedTargetsRef.current.add(voiceTarget); retargetListening(voiceTarget); }, [listening, retargetListening, voiceTarget]);
    useEffect(() => { setCodingEnabled(activeRound?.deliveryMode === "online-assessment" || /\b(code|implement|algorithm|data structure|complexity|function|program)\b/i.test(activeQuestion?.text || "")); }, [activeQuestion?._id, activeQuestion?.text, activeRound?.deliveryMode]);
    useEffect(() => { setFocusedField(activeQuestion?.followUpQuestion ? "followup" : codingEnabled ? "spoken" : "answer"); }, [activeQuestion?._id, activeQuestion?.followUpQuestion, codingEnabled]);
    useEffect(() => {
        if (!attempt || !activeQuestion || !supportsSTT || busy || listening || autoStartedTargetsRef.current.has(voiceTarget)) return undefined;
        let checks = 0;
        const timer = setInterval(() => {
            checks += 1;
            if (window.speechSynthesis?.speaking && checks < 60) return;
            clearInterval(timer); autoStartedTargetsRef.current.add(voiceTarget); startListening(voiceTarget);
        }, 250);
        return () => clearInterval(timer);
    }, [activeQuestion, attempt, busy, listening, startListening, supportsSTT, voiceTarget]);
    useEffect(() => { const spokenText = activeQuestion?.followUpQuestion || activeQuestion?.text; if (!supportsTTS || !spokenText) return undefined; const timer = setTimeout(() => speakNow(spokenText), 400); return () => { clearTimeout(timer); try { window.speechSynthesis?.cancel(); } catch { /* no-op */ } }; }, [activeQuestion?._id, activeQuestion?.followUpQuestion, activeQuestion?.text, speakNow, supportsTTS]);
    const goToNextQuestion = () => { if (!attempt) return; if (activeQuestionIndex + 1 < activeRound.questions.length) setActiveQuestionIndex(activeQuestionIndex + 1); else if (activeRoundIndex + 1 < attempt.rounds.length) { setActiveRoundIndex(activeRoundIndex + 1); setActiveQuestionIndex(0); } };
    const submit = async () => { setBusy(true); setError(""); try { await api.post(`/assessments/public/${shareToken}/attempts/${attempt._id}/submit`, {}, { headers: { "X-Attempt-Token": attemptToken }, skipAuthRedirect: true }); localStorage.removeItem(storageKey); setSubmitted(true); } catch (err) { setError(err?.response?.data?.message || "Your assessment could not be submitted."); } finally { setBusy(false); } };
    if (loading) return <Stack minHeight="70vh" justifyContent="center" alignItems="center"><CircularProgress /></Stack>;
    if (!assessment) return <Container maxWidth="sm" sx={{ py: 8 }}><Alert severity="error">{error}</Alert></Container>;
    if (submitted) return <Container maxWidth="sm" sx={{ py: 8 }}><Paper variant="outlined" sx={{ p: 5, textAlign: "center" }}><Typography variant="h4" fontWeight={850}>Assessment submitted</Typography><Typography color="text.secondary" mt={2}>Your responses were sent to the interviewer. You can safely close this page.</Typography></Paper></Container>;
    return <Container maxWidth="lg" sx={{ py: { xs: 3, md: 5 } }}>
        <Typography variant="overline" color="primary" fontWeight={800}>{assessment.company || "Candidate assessment"}</Typography><Typography component="h1" variant="h3" sx={{ fontSize: { xs: "2.45rem", sm: "3rem" } }} fontWeight={850}>{assessment.title}</Typography><Typography color="text.secondary" mt={1}>{assessment.jobRole} · {assessment.rounds.reduce((sum, round) => sum + round.questionCount, 0)} {assessment.rounds.reduce((sum, round) => sum + round.questionCount, 0) === 1 ? "question" : "questions"} · about {assessment.durationMinutes || 30} minutes{assessment.followUpsEnabled ? " · contextual follow-ups enabled" : ""}</Typography>
        {assessment.expiresAt && <Typography variant="body2" color="text.secondary" mt={1}>Submit by {new Date(assessment.expiresAt).toLocaleString()}</Typography>}
        {assessment.candidateInstructions && <Alert severity="info" sx={{ mt: 3 }}>{assessment.candidateInstructions}</Alert>}{error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}
        {!attempt ? <Paper component="form" onSubmit={start} variant="outlined" sx={{ p: { xs: 2, md: 4 }, mt: 3 }}><Typography component="h2" variant="h5" fontWeight={800}>Before you begin</Typography><Typography color="text.secondary" mt={1} mb={3}>Your identity, answers, and AI-generated evaluation will be shared with the interviewer. Scores and feedback are not shown to candidates.</Typography><Stack spacing={2}><TextField required label="Full name" value={identity.name} onChange={(e) => setIdentity({ ...identity, name: e.target.value })} /><TextField required type="email" label="Email address" value={identity.email} onChange={(e) => setIdentity({ ...identity, email: e.target.value })} /><FormControlLabel control={<Checkbox required checked={consent} onChange={(event) => setConsent(event.target.checked)} />} label={<span>I understand how my assessment data is processed and shared. <Link component={RouterLink} to="/privacy" target="_blank">Privacy notice</Link></span>} />{assessment.integrity?.enabled && <Alert severity="warning"><Typography fontWeight={750}>Integrity signals are enabled</Typography><Typography variant="body2">The interviewer may review tab visibility, window focus, fullscreen, clipboard, and connectivity events. These are context—not automatic cheating findings—and are retained for {assessment.integrity.retentionDays || 30} days.</Typography><FormControlLabel control={<Checkbox required checked={integrityConsent} onChange={(event) => setIntegrityConsent(event.target.checked)} />} label="I consent to these integrity signals" />{assessment.integrity.requireCamera && <Button size="small" variant={cameraReady ? "outlined" : "contained"} color={cameraReady ? "success" : "primary"} onClick={checkCamera}>{cameraReady ? "Camera ready" : "Check camera"}</Button>}</Alert>}{assessment.contactEmail && <Typography variant="body2" color="text.secondary">Need an accommodation or technical help? Contact <Link href={`mailto:${assessment.contactEmail}`}>{assessment.contactEmail}</Link>.</Typography>}<Box><Button type="submit" variant="contained" disabled={busy || !consent || (assessment.integrity?.enabled && !integrityConsent) || (assessment.integrity?.requireCamera && !cameraReady)}>{busy ? <CircularProgress size={22} color="inherit" /> : "Start assessment"}</Button></Box></Stack></Paper> : <Box mt={4}>
            <Stack direction="row" justifyContent="space-between" mb={1}><Typography fontWeight={750}>Interview progress</Typography><Typography>{completed} of {questions.length} complete</Typography></Stack><LinearProgress variant="determinate" value={questions.length ? completed / questions.length * 100 : 0} sx={{ mb: 3, height: 8, borderRadius: 4 }} />
            <Box sx={{ display: "flex", gap: 3, flexDirection: { xs: "column", md: "row" } }}>
                <Stack spacing={1.5} sx={{ width: { xs: "100%", md: 250 }, flexShrink: 0 }}>{attempt.rounds.map((round, roundIndex) => { const answered = round.questions.filter((question) => question.answer && (!question.followUpQuestion || question.followUpAnswer)).length; return <Paper variant="outlined" key={round._id} sx={{ overflow: "hidden", borderColor: activeRoundIndex === roundIndex ? "primary.main" : "divider", borderWidth: activeRoundIndex === roundIndex ? 2 : 1 }}><Button fullWidth onClick={() => { setActiveRoundIndex(roundIndex); setActiveQuestionIndex(0); }} sx={{ p: 2, display: "block", textAlign: "left", color: "text.primary" }}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>{round.name}</Typography><Typography variant="caption">{answered}/{round.questions.length}</Typography></Stack><LinearProgress variant="determinate" value={round.questions.length ? answered / round.questions.length * 100 : 0} sx={{ mt: 1 }} /><Typography variant="caption" color="text.secondary">{round.deliveryMode === "online-assessment" ? "Coding / written" : "Conversational"}</Typography></Button></Paper>; })}</Stack>
                <Box sx={{ flex: 1, minWidth: 0 }}>{activeQuestion && <Card variant="outlined"><CardContent sx={{ p: { xs: 2, md: 3 } }}><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" gap={1}><Box><Typography variant="overline" color="primary" fontWeight={800}>{activeRound.name} · Question {activeQuestionIndex + 1} of {activeRound.questions.length}</Typography><Typography component="h2" variant="h5" fontWeight={800}>{activeQuestion.text}</Typography></Box>{activeQuestion.answer && <Chip label={dirty[answerKey(activeRoundIndex, activeQuestionIndex)] ? "Unsaved changes" : "Saved"} size="small" color={dirty[answerKey(activeRoundIndex, activeQuestionIndex)] ? "warning" : "success"} />}</Stack>
                    <Box sx={{ position: "relative", minHeight: 150, mt: 2, borderRadius: 2, bgcolor: "#111827", overflow: "hidden", display: "flex", alignItems: "center", justifyContent: "center", px: 20 }}><Typography color="rgba(255,255,255,.65)" textAlign="center">Interview in progress</Typography><WebcamPreview autoStart /></Box>
                    <Box mt={2}><VoiceControls target={voiceTarget} speakText={activeQuestion.text} supportsTTS={supportsTTS} supportsSTT={supportsSTT} listening={listening} listeningTarget={listeningTarget} onSpeak={speakNow} onStartListening={startListening} onStopListening={stopListening} micPermission={micPermission} micLevel={micLevel} inputDevices={inputDevices} selectedDeviceId={selectedDeviceId} onChangeDevice={setSelectedDeviceId} /><Typography variant="caption" color="text.secondary">Voice will fill: {focusedField === "spoken" ? "Spoken explanation" : focusedField === "followup" ? "Follow-up answer" : "Answer"}. Pauses insert completed speech while the microphone stays on.</Typography></Box>
                    {listening && listeningTarget === voiceTarget && interimText && <Alert severity="info" sx={{ mt: 1 }}>Listening: {interimText}</Alert>}
                    <Box mt={2}><CodeEditorField value={activeQuestion.answer || ""} onChange={(value) => updateLocal(activeRoundIndex, activeQuestionIndex, "answer", value)} onFocus={() => setFocusedField("answer")} minRows={6} draftKey={`candidate:${attempt._id}:${activeRound._id}:${activeQuestion._id}`} suggestCode={activeRound.deliveryMode === "online-assessment" && /\b(code|coding|implement|algorithm|function|class|program)\b/i.test(activeQuestion.text)} onModeChange={setCodingEnabled} executionEndpoint={`${candidateToolBase}/run-code`} executionHeaders={candidateToolHeaders} skipAuthRedirect canRun={assessment.capabilities?.codeExecution !== false} /></Box>
                    {codingEnabled && <TextField fullWidth multiline minRows={3} sx={{ mt: 2 }} label="Spoken explanation" helperText="Focus this field, then stop recording to place speech here." value={spokenNotes[answerTarget] ?? activeQuestion.spokenExplanation ?? ""} onFocus={() => setFocusedField("spoken")} onChange={(event) => { setSpokenNotes((current) => ({ ...current, [answerTarget]: event.target.value })); setDirty((current) => ({ ...current, [answerKey(activeRoundIndex, activeQuestionIndex)]: true })); }} />}
                    {codingEnabled && assessment.capabilities?.codeExecution === false && <Alert severity="info" sx={{ mt: 1 }}>Code execution is unavailable, but you can still write and submit code.</Alert>}
                    {assessment.capabilities?.transcription === false && <Alert severity="info" sx={{ mt: 1 }}>Server transcription is unavailable. Browser voice input will be used when supported.</Alert>}
                    <Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" gap={1} mt={2}><Button disabled={activeRoundIndex === 0 && activeQuestionIndex === 0} onClick={() => { if (activeQuestionIndex > 0) setActiveQuestionIndex(activeQuestionIndex - 1); else { const previousRound = activeRoundIndex - 1; setActiveRoundIndex(previousRound); setActiveQuestionIndex(attempt.rounds[previousRound].questions.length - 1); } }}>Previous</Button><Button variant="contained" disabled={busy || !activeQuestion.answer?.trim() || !dirty[answerKey(activeRoundIndex, activeQuestionIndex)]} onClick={async () => { const saved = await saveAnswer(activeRoundIndex, activeQuestionIndex, false, spokenNotes[answerTarget] ?? activeQuestion.spokenExplanation); if (saved && !assessment.followUpsEnabled) goToNextQuestion(); }}>Save answer{assessment.followUpsEnabled && !activeQuestion.followUpQuestion ? " and get follow-up" : ""}</Button></Stack>
                    {activeQuestion.followUpQuestion && <Box sx={{ mt: 3, pl: 2, borderLeft: "3px solid", borderColor: "primary.main" }}><Typography fontWeight={750}>Follow-up: {activeQuestion.followUpQuestion}</Typography><TextField fullWidth multiline minRows={3} sx={{ mt: 1 }} label="Your follow-up answer" value={activeQuestion.followUpAnswer || ""} onFocus={() => setFocusedField("followup")} onChange={(e) => updateLocal(activeRoundIndex, activeQuestionIndex, "followUpAnswer", e.target.value)} /><Button sx={{ mt: 1 }} variant="outlined" disabled={busy || !activeQuestion.followUpAnswer?.trim() || !dirty[answerKey(activeRoundIndex, activeQuestionIndex, true)]} onClick={async () => { if (await saveAnswer(activeRoundIndex, activeQuestionIndex, true)) goToNextQuestion(); }}>Save follow-up and continue</Button></Box>}
                </CardContent></Card>}</Box>
            </Box>
            <Paper variant="outlined" sx={{ p: 3, mt: 3 }}><Typography fontWeight={800}>Ready to submit?</Typography><Typography color="text.secondary" variant="body2" mt={.5}>Submission is final. Your report will be visible only to the interviewer.</Typography>{Object.keys(dirty).length > 0 && <Alert severity="warning" sx={{ mt: 2 }}>Save all changes before submitting.</Alert>}<Button variant="contained" sx={{ mt: 2 }} disabled={busy || completed !== questions.length || Object.keys(dirty).length > 0} onClick={submit}>{busy ? <CircularProgress size={22} color="inherit" /> : "Submit assessment"}</Button></Paper>
        </Box>}
    </Container>;
}
