import { useEffect, useMemo, useState } from "react";
import { Link as RouterLink, useParams } from "react-router-dom";
import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, CircularProgress, Container, FormControlLabel, LinearProgress, Link, Paper, Stack, TextField, Typography } from "@mui/material";
import api from "../api/axios";

export default function CandidateAssessmentPage() {
    const { shareToken } = useParams(); const storageKey = `assessment-attempt:${shareToken}`;
    const [assessment, setAssessment] = useState(null); const [attempt, setAttempt] = useState(null); const [attemptToken, setAttemptToken] = useState("");
    const [identity, setIdentity] = useState({ name: "", email: "" }); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [submitted, setSubmitted] = useState(false);
    const [consent, setConsent] = useState(false); const [dirty, setDirty] = useState({});
    useEffect(() => { (async () => { try { const { data } = await api.get(`/assessments/public/${shareToken}`); setAssessment(data); const saved = JSON.parse(sessionStorage.getItem(storageKey) || "null"); if (saved?.attempt && saved?.attemptToken) { setAttempt(saved.attempt); setAttemptToken(saved.attemptToken); } } catch { setError("This assessment link is invalid, closed, or expired."); } finally { setLoading(false); } })(); }, [shareToken, storageKey]);
    const persist = (nextAttempt, token = attemptToken) => { setAttempt(nextAttempt); sessionStorage.setItem(storageKey, JSON.stringify({ attempt: nextAttempt, attemptToken: token })); };
    const start = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { const { data } = await api.post(`/assessments/public/${shareToken}/start`, identity, { skipAuthRedirect: true }); setAttemptToken(data.attemptToken); persist(data.attempt, data.attemptToken); } catch (err) { setError(err?.response?.data?.message || "We couldn’t start your assessment."); } finally { setBusy(false); } };
    useEffect(() => { const warn = (event) => { if (!Object.keys(dirty).length) return; event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
    const answerKey = (roundIndex, questionIndex, followUp = false) => `${roundIndex}:${questionIndex}:${followUp ? "followup" : "answer"}`;
    const updateLocal = (roundIndex, questionIndex, key, value) => { setDirty((current) => ({ ...current, [answerKey(roundIndex, questionIndex, key === "followUpAnswer")]: true })); setAttempt((current) => ({ ...current, rounds: current.rounds.map((round, ri) => ri === roundIndex ? { ...round, questions: round.questions.map((question, qi) => qi === questionIndex ? { ...question, [key]: value } : question) } : round) })); };
    const saveAnswer = async (roundIndex, questionIndex, followUp = false) => { const question = attempt.rounds[roundIndex].questions[questionIndex]; const value = followUp ? question.followUpAnswer : question.answer; if (!value?.trim()) { setError("Write an answer before saving."); return; } setBusy(true); setError(""); try { const body = { roundIndex, questionIndex, [followUp ? "followUpAnswer" : "answer"]: value }; const { data } = await api.put(`/assessments/public/${shareToken}/attempts/${attempt._id}/answer`, body, { headers: { "X-Attempt-Token": attemptToken }, skipAuthRedirect: true }); persist(data.attempt); const key = answerKey(roundIndex, questionIndex, followUp); setDirty((current) => { const next = { ...current }; delete next[key]; return next; }); } catch (err) { setError(err?.response?.data?.message || "Your answer could not be saved."); } finally { setBusy(false); } };
    const questions = useMemo(() => attempt?.rounds?.flatMap((round) => round.questions) || [], [attempt]); const completed = questions.filter((question) => question.answer && (!question.followUpQuestion || question.followUpAnswer)).length;
    const submit = async () => { setBusy(true); setError(""); try { await api.post(`/assessments/public/${shareToken}/attempts/${attempt._id}/submit`, {}, { headers: { "X-Attempt-Token": attemptToken }, skipAuthRedirect: true }); sessionStorage.removeItem(storageKey); setSubmitted(true); } catch (err) { setError(err?.response?.data?.message || "Your assessment could not be submitted."); } finally { setBusy(false); } };
    if (loading) return <Stack minHeight="70vh" justifyContent="center" alignItems="center"><CircularProgress /></Stack>;
    if (!assessment) return <Container maxWidth="sm" sx={{ py: 8 }}><Alert severity="error">{error}</Alert></Container>;
    if (submitted) return <Container maxWidth="sm" sx={{ py: 8 }}><Paper variant="outlined" sx={{ p: 5, textAlign: "center" }}><Typography variant="h4" fontWeight={850}>Assessment submitted</Typography><Typography color="text.secondary" mt={2}>Your responses were sent to the interviewer. You can safely close this page.</Typography></Paper></Container>;
    return <Container maxWidth="md" sx={{ py: { xs: 3, md: 6 } }}>
        <Typography variant="overline" color="primary" fontWeight={800}>{assessment.company || "Candidate assessment"}</Typography><Typography component="h1" variant="h3" sx={{ fontSize: { xs: "2.45rem", sm: "3rem" } }} fontWeight={850}>{assessment.title}</Typography><Typography color="text.secondary" mt={1}>{assessment.jobRole} · {assessment.rounds.reduce((sum, round) => sum + round.questionCount, 0)} {assessment.rounds.reduce((sum, round) => sum + round.questionCount, 0) === 1 ? "question" : "questions"} · about {assessment.durationMinutes || 30} minutes{assessment.followUpsEnabled ? " · contextual follow-ups enabled" : ""}</Typography>
        {assessment.expiresAt && <Typography variant="body2" color="text.secondary" mt={1}>Submit by {new Date(assessment.expiresAt).toLocaleString()}</Typography>}
        {assessment.candidateInstructions && <Alert severity="info" sx={{ mt: 3 }}>{assessment.candidateInstructions}</Alert>}{error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}
        {!attempt ? <Paper component="form" onSubmit={start} variant="outlined" sx={{ p: { xs: 2, md: 4 }, mt: 3 }}><Typography component="h2" variant="h5" fontWeight={800}>Before you begin</Typography><Typography color="text.secondary" mt={1} mb={3}>Your identity, answers, and AI-generated evaluation will be shared with the interviewer. Scores and feedback are not shown to candidates.</Typography><Stack spacing={2}><TextField required label="Full name" value={identity.name} onChange={(e) => setIdentity({ ...identity, name: e.target.value })} /><TextField required type="email" label="Email address" value={identity.email} onChange={(e) => setIdentity({ ...identity, email: e.target.value })} /><FormControlLabel control={<Checkbox required checked={consent} onChange={(event) => setConsent(event.target.checked)} />} label={<span>I understand how my assessment data is processed and shared. <Link component={RouterLink} to="/privacy" target="_blank">Privacy notice</Link></span>} />{assessment.contactEmail && <Typography variant="body2" color="text.secondary">Need an accommodation or technical help? Contact <Link href={`mailto:${assessment.contactEmail}`}>{assessment.contactEmail}</Link>.</Typography>}<Box><Button type="submit" variant="contained" disabled={busy || !consent}>{busy ? <CircularProgress size={22} color="inherit" /> : "Start assessment"}</Button></Box></Stack></Paper> : <Box mt={4}>
            <Stack direction="row" justifyContent="space-between" mb={1}><Typography fontWeight={750}>Progress</Typography><Typography>{completed} of {questions.length} complete</Typography></Stack><LinearProgress variant="determinate" value={questions.length ? completed / questions.length * 100 : 0} sx={{ mb: 3, height: 8, borderRadius: 4 }} />
            <Stack spacing={3}>{attempt.rounds.map((round, roundIndex) => <Box key={round._id}><Typography component="h2" variant="h5" fontWeight={800} mb={1}>{round.name}</Typography>{round.description && <Typography color="text.secondary" mb={2}>{round.description}</Typography>}<Stack spacing={2}>{round.questions.map((question, questionIndex) => { const answerDirty = dirty[answerKey(roundIndex, questionIndex)]; return <Card variant="outlined" key={question._id}><CardContent><Stack direction="row" justifyContent="space-between" gap={1}><Typography component="h3" fontWeight={750}>{questionIndex + 1}. {question.text}</Typography>{question.answer && <Chip label={answerDirty ? "Unsaved changes" : "Saved"} size="small" color={answerDirty ? "warning" : "success"} />}</Stack><TextField fullWidth multiline minRows={4} sx={{ mt: 2 }} label="Your answer" value={question.answer || ""} onChange={(e) => updateLocal(roundIndex, questionIndex, "answer", e.target.value)} inputProps={{ maxLength: 5000 }} /><Button sx={{ mt: 1 }} variant="outlined" disabled={busy || !question.answer?.trim() || !answerDirty} onClick={() => saveAnswer(roundIndex, questionIndex)}>Save answer{assessment.followUpsEnabled && !question.followUpQuestion ? " and get follow-up" : ""}</Button>{question.followUpQuestion && <Box sx={{ mt: 3, pl: 2, borderLeft: "3px solid", borderColor: "primary.main" }}><Typography fontWeight={750}>Follow-up: {question.followUpQuestion}</Typography><TextField fullWidth multiline minRows={3} sx={{ mt: 1 }} label="Your follow-up answer" value={question.followUpAnswer || ""} onChange={(e) => updateLocal(roundIndex, questionIndex, "followUpAnswer", e.target.value)} /><Button sx={{ mt: 1 }} variant="outlined" disabled={busy || !question.followUpAnswer?.trim() || !dirty[answerKey(roundIndex, questionIndex, true)]} onClick={() => saveAnswer(roundIndex, questionIndex, true)}>Save follow-up</Button></Box>}</CardContent></Card>; })}</Stack></Box>)}</Stack>
            <Paper variant="outlined" sx={{ p: 3, mt: 3 }}><Typography fontWeight={800}>Ready to submit?</Typography><Typography color="text.secondary" variant="body2" mt={.5}>Submission is final. Your report will be visible only to the interviewer.</Typography>{Object.keys(dirty).length > 0 && <Alert severity="warning" sx={{ mt: 2 }}>Save all changes before submitting.</Alert>}<Button variant="contained" sx={{ mt: 2 }} disabled={busy || completed !== questions.length || Object.keys(dirty).length > 0} onClick={submit}>{busy ? <CircularProgress size={22} color="inherit" /> : "Submit assessment"}</Button></Paper>
        </Box>}
    </Container>;
}
