import express from "express";
import { z } from "zod";
import protect from "../middleware/authMiddleware.js";
import validate from "../middleware/validate.js";
import quotas from "../middleware/quotas.js";
import usageLimit from "../middleware/usageLimit.js";
import requireFeature from "../middleware/featureFlags.js";
import { uploadAudioMulter } from "../middleware/multerMemory.js";
import { ObjectIdString } from "../validation/commonSchemas.js";
import audit from "../middleware/audit.js";
import {
    createAssessment, getAssessmentReport, getHiringOverview, getPublicAssessment, listAssessments,
    duplicateAssessment, generateAssessmentQuestions, improveAssessmentQuestionText, inviteCandidates, previewAssessment, protectCandidateTool, recordIntegrityEvent, reviewCandidateAttempt, revokeInvitation, runCandidateCode, saveCandidateAnswer, startCandidateAttempt, submitCandidateAttempt, transcribeCandidateAudio, updateAssessment,
} from "../controllers/assessmentController.js";

const router = express.Router();
const questionInput = z.object({ text: z.string().trim().min(5).max(1000), weight: z.coerce.number().min(.1).max(10).optional().default(1), competencies: z.array(z.string().trim().min(1).max(80)).max(10).optional().default([]), knockout: z.boolean().optional().default(false) });
const roundInput = z.object({ name: z.string().trim().min(2).max(80), description: z.string().trim().max(300).optional().default(""), deliveryMode: z.enum(["conversational", "online-assessment"]).optional().default("conversational"), aiPrompt: z.string().trim().max(1000).optional().default(""), questionCount: z.coerce.number().int().min(1).max(10), questions: z.array(questionInput).max(10).optional().default([]) });
const attemptParams = z.object({ shareToken: z.string().min(20).max(100), attemptId: ObjectIdString });
const validTimezone = (value) => { try { Intl.DateTimeFormat("en-US", { timeZone: value }); return true; } catch { return false; } };
const optionalDate = z.union([z.literal(""), z.null(), z.coerce.date()]).optional();
const assessmentEditable = z.object({ title: z.string().trim().min(2).max(160), company: z.string().trim().max(120).optional().default(""), jobRole: z.string().trim().min(2).max(120), jobDescription: z.string().trim().min(20).max(4000), followUpsEnabled: z.boolean().optional().default(true), inviteOnly: z.boolean().optional().default(false), candidateInstructions: z.string().trim().max(1200).optional().default(""), contactEmail: z.union([z.string().trim().email().max(254), z.literal("")]).optional().default(""), durationMinutes: z.coerce.number().int().min(5).max(240).optional().default(30), opensAt: optionalDate, expiresAt: optionalDate, timezone: z.string().trim().max(100).refine(validTimezone, "Choose a valid IANA timezone").optional().default("UTC"), integrity: z.object({ enabled: z.boolean().default(false), requireFullscreen: z.boolean().default(false), trackFocus: z.boolean().default(true), trackClipboard: z.boolean().default(true), requireCamera: z.boolean().default(false), monitorFacePresence: z.boolean().default(false), retentionDays: z.coerce.number().int().min(1).max(365).default(30) }).optional(), rubric: z.array(z.object({ name: z.string().trim().min(2).max(80), description: z.string().trim().max(300).optional().default(""), weight: z.coerce.number().min(1).max(100).default(1) })).max(12).optional().default([]), templateName: z.string().trim().max(160).optional().default(""), rounds: z.array(roundInput).min(1).max(5) });

router.get("/public/:shareToken", validate(z.object({ shareToken: z.string().min(20).max(100) }), "params"), validate(z.object({ invite: ObjectIdString.optional() }), "query"), getPublicAssessment);
router.post("/public/:shareToken/start", quotas({ key: (req) => `assessment-start:${req.params.shareToken}:${req.ip}`, metricKey: "assessment_start", windowSeconds: 3600, maxPerWindow: 10 }), validate(z.object({ shareToken: z.string().min(20).max(100) }), "params"), validate(z.object({ name: z.string().trim().min(1).max(120), email: z.string().trim().email().max(254), integrityConsent: z.boolean().optional().default(false) })), startCandidateAttempt);
router.put("/public/:shareToken/attempts/:attemptId/answer", quotas({ key: (req) => `assessment-answer:${req.params.attemptId}:${req.ip}`, metricKey: "assessment_answer", windowSeconds: 3600, maxPerWindow: 60 }), validate(attemptParams, "params"), validate(z.object({ roundIndex: z.number().int().min(0).max(4), questionIndex: z.number().int().min(0).max(19), answer: z.string().max(20000).optional(), spokenExplanation: z.string().max(5000).optional(), followUpAnswer: z.string().max(5000).optional() }).refine((body) => body.answer !== undefined || body.spokenExplanation !== undefined || body.followUpAnswer !== undefined)), saveCandidateAnswer);
router.post("/public/:shareToken/attempts/:attemptId/submit", quotas({ key: (req) => `assessment-submit:${req.params.attemptId}:${req.ip}`, metricKey: "assessment_submit", windowSeconds: 3600, maxPerWindow: 5 }), validate(attemptParams, "params"), submitCandidateAttempt);
router.post("/public/:shareToken/attempts/:attemptId/integrity-events", quotas({ key: (req) => `assessment-integrity:${req.params.attemptId}:${req.ip}`, metricKey: "assessment_integrity", windowSeconds: 3600, maxPerWindow: 500 }), validate(attemptParams, "params"), validate(z.object({ type: z.enum(["tab_hidden", "window_blur", "fullscreen_exit", "copy", "paste", "offline", "online", "face_missing", "face_restored", "multiple_faces", "camera_interrupted", "face_detection_unavailable"]), metadata: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()])).optional().default({}) })), recordIntegrityEvent);
router.post("/public/:shareToken/attempts/:attemptId/run-code", requireFeature("ENABLE_CODE_EXEC"), validate(attemptParams, "params"), protectCandidateTool, quotas({ key: (req) => `assessment-code:${req.params.attemptId}:${req.ip}`, metricKey: "assessment_run_code", windowSeconds: 3600, maxPerWindow: 120 }), validate(z.object({ language: z.enum(["javascript", "python", "cpp", "java"]), code: z.string().min(1).max(20000), stdin: z.string().max(20000).optional() })), runCandidateCode);
router.post("/public/:shareToken/attempts/:attemptId/transcribe", requireFeature("ENABLE_STT"), validate(attemptParams, "params"), protectCandidateTool, quotas({ key: (req) => `assessment-stt:${req.params.attemptId}:${req.ip}`, metricKey: "assessment_stt", windowSeconds: 3600, maxPerWindow: 120 }), uploadAudioMulter.single("audio"), transcribeCandidateAudio);

router.get("/", protect, listAssessments);
router.get("/overview", protect, validate(z.object({ page: z.coerce.number().int().min(1).optional(), limit: z.coerce.number().int().min(1).max(50).optional(), search: z.string().trim().max(100).optional(), status: z.enum(["started", "evaluating", "submitted", "evaluation_failed"]).optional(), assessmentId: ObjectIdString.optional() }), "query"), getHiringOverview);
router.post("/questions/generate", protect, quotas({ key: (req) => `assessment-question-generate:${req.user._id}`, metricKey: "assessment_question_generate", windowSeconds: 3600, maxPerWindow: 30 }), validate(z.object({ company: z.string().trim().max(120).optional().default(""), jobRole: z.string().trim().min(2).max(120), jobDescription: z.string().trim().min(20).max(4000), roundName: z.string().trim().min(2).max(80), roundDescription: z.string().trim().max(300).optional().default(""), prompt: z.string().trim().min(3).max(1000), count: z.coerce.number().int().min(1).max(10), existingQuestions: z.array(z.string().trim().min(5).max(1000)).max(20).optional().default([]) })), generateAssessmentQuestions);
router.post("/questions/improve", protect, quotas({ key: (req) => `assessment-question-improve:${req.user._id}`, metricKey: "assessment_question_improve", windowSeconds: 3600, maxPerWindow: 60 }), validate(z.object({ question: z.string().trim().min(5).max(1000), instruction: z.string().trim().max(500).optional().default(""), jobRole: z.string().trim().max(120).optional().default(""), jobDescription: z.string().trim().max(4000).optional().default(""), roundName: z.string().trim().max(80).optional().default("") })), improveAssessmentQuestionText);
router.post("/", protect, usageLimit("assessments", "assessmentsPerMonth"), validate(assessmentEditable.extend({ status: z.enum(["draft", "scheduled", "active"]).optional().default("draft") })), audit("assessment.create", { entityType: "Assessment", pickBody: (body) => ({ status: body.status, inviteOnly: body.inviteOnly, rounds: body.rounds?.length, integrityEnabled: body.integrity?.enabled }) }), createAssessment);
router.get("/:assessmentId", protect, validate(z.object({ assessmentId: ObjectIdString }), "params"), getAssessmentReport);
router.get("/:assessmentId/preview", protect, validate(z.object({ assessmentId: ObjectIdString }), "params"), previewAssessment);
router.post("/:assessmentId/duplicate", protect, validate(z.object({ assessmentId: ObjectIdString }), "params"), validate(z.object({ title: z.string().trim().min(2).max(160).optional() })), audit("assessment.duplicate", { entityType: "Assessment", getEntityId: (_req, _body, response) => response?._id }), duplicateAssessment);
router.post("/:assessmentId/invitations", protect, validate(z.object({ assessmentId: ObjectIdString }), "params"), validate(z.object({ candidates: z.array(z.object({ email: z.string().trim().email().max(254), name: z.string().trim().max(120).optional().default("") })).min(1).max(100) })), audit("assessment.invite", { entityType: "Assessment", getEntityId: (req) => req.params.assessmentId, pickBody: (body) => ({ candidateCount: body.candidates?.length }) }), inviteCandidates);
router.delete("/:assessmentId/invitations/:invitationId", protect, validate(z.object({ assessmentId: ObjectIdString, invitationId: ObjectIdString }), "params"), audit("assessment.invitation.revoke", { entityType: "Assessment", getEntityId: (req) => req.params.assessmentId }), revokeInvitation);
router.patch("/:assessmentId/attempts/:attemptId/review", protect, validate(z.object({ assessmentId: ObjectIdString, attemptId: ObjectIdString }), "params"), validate(z.object({ reviewerScore: z.coerce.number().min(0).max(10), reviewerDecision: z.enum(["", "advance", "hold", "reject"]), reviewerNotes: z.string().trim().max(5000).optional().default(""), reviewerRatings: z.array(z.object({ criterion: z.string().trim().min(1).max(80), score: z.coerce.number().min(0).max(10), note: z.string().trim().max(1000).optional().default("") })).max(12).optional().default([]) })), audit("assessment.review", { entityType: "CandidateAttempt", getEntityId: (req) => req.params.attemptId, pickBody: (body) => ({ reviewerScore: body.reviewerScore, reviewerDecision: body.reviewerDecision, ratingCount: body.reviewerRatings?.length }) }), reviewCandidateAttempt);
router.patch("/:assessmentId", protect, validate(z.object({ assessmentId: ObjectIdString }), "params"), validate(z.union([z.object({ status: z.enum(["draft", "scheduled", "active", "closed", "archived"]) }), assessmentEditable])), audit("assessment.update", { entityType: "Assessment", getEntityId: (req) => req.params.assessmentId, pickBody: (body) => ({ status: body.status, contentUpdated: !body.status }) }), updateAssessment);

export default router;
